### ISSUE TITLE
how can I spin up new page when the resume is Full

### ISSUE THREAD

**Issue by iliass373** [ArthurBernard/Arthur-CV-LaTeX#1]
I was following this template since 2021, and now, my resume need more space 

I tried many stuffs to spin up new pages rather than overflows the text, but it doesn't work

do you have any information to help ?

Many Thanks

**Comment by ArthurBernard** [comment]
I have added an example of a 2-page CV, it is in the 'two_pages' branch.

It's a quick fix, I haven't had time to modify the template, I'll do it later, or you can contribute if you like.

Here is the code I added between two textblock to create a new page:

```latex
\end{textblock}

%%%%%%%%%%%%%%%%%%%%%%
%%  Add a new page  %%
%%%%%%%%%%%%%%%%%%%%%%

\newpage

\begin{tikzpicture}[remember picture,overlay]
  \node [rectangle, anchor=north west, fill=leftcolorband, minimum width=8cm, minimum height=30.5cm] at (0cm, 0.5cm) {};{};
\end{tikzpicture}

\begin{textblock}{20.5}(0.25, 0.0)
```

Let me know if it's working for you

**Comment by ArthurBernard** [comment]
Finally I created a new command in the template `arthur-cv.cls`, you just need to use the `\newcvpage` command to add a new page to your CV. See `./example/Two_Pages_CV.tex` for more details.

I close the issue and I merge the `two_pages` branch to `master`.

Let me know if it's not working for you

**Comment by iliass373** [comment]
Indeed, I did, and it works like wanted 

Thank you
